services:
  - type: web
    name: ranhentos-idiomas-api
    runtime: image
    repo: https://github.com/Ezequias-Rodrigues/CRUD---Ranhentos-Idiomas
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: sql.freedb.tech
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: freedb_ranhentos_idiomas
      - key: DB_USERNAME
        value: freedb_ranhentos_user
      - key: DB_PASSWORD
        value: a&9N5@qqUkS9fMJ
